import {useEffect,useState} from 'react';
import {conflicts,makeSudoku,sudokuHint,type SudokuHint,type Difficulty} from '../games/sudoku';
import './MiniSudoku.css';
type Move={board:number[];notes:number[][]};
export default function MiniSudoku(){
  const [size,setSize]=useState(6),[difficulty,setDifficulty]=useState<Difficulty>('Medium'),[seed,setSeed]=useState(()=>Date.now()>>>0);
  const [puzzle,setPuzzle]=useState(()=>makeSudoku(6,'Medium',seed));
  const [board,setBoard]=useState(puzzle.givens),[notes,setNotes]=useState<number[][]>(()=>puzzle.givens.map(()=>[]));
  const [selected,setSelected]=useState(()=>puzzle.givens.findIndex(value=>!value)),[noteMode,setNoteMode]=useState(false),[history,setHistory]=useState<Move[]>([]),[hints,setHints]=useState(3),[seconds,setSeconds]=useState(0),[message,setMessage]=useState('Select an empty cell and choose a number.');
  const [hintCard,setHintCard]=useState<SudokuHint|null>(null);
  const won=board.every((value,i)=>value===puzzle.solution[i]);
  useEffect(()=>{if(won)return;const id=setInterval(()=>setSeconds(value=>value+1),1000);return()=>clearInterval(id)},[won,seed]);
  function start(nextSize=size,nextDifficulty=difficulty){const nextSeed=(Date.now()+Math.floor(Math.random()*100000))>>>0,next=makeSudoku(nextSize,nextDifficulty,nextSeed);setSize(nextSize);setDifficulty(nextDifficulty);setSeed(nextSeed);setPuzzle(next);setBoard(next.givens);setNotes(next.givens.map(()=>[]));setSelected(next.givens.findIndex(value=>!value));setHistory([]);setHints(3);setSeconds(0);setNoteMode(false);setHintCard(null);setMessage('New puzzle ready. Each row, column and box needs every digit once.')}
  function snapshot(){setHistory(previous=>[...previous,{board:[...board],notes:notes.map(values=>[...values])}])}
  function enter(value:number){if(won)return;setHintCard(null);if(puzzle.givens[selected]){setMessage('That number is a fixed clue. Select an empty cell.');return}snapshot();if(noteMode&&value){setNotes(previous=>previous.map((values,i)=>i!==selected?values:values.includes(value)?values.filter(n=>n!==value):[...values,value].sort()));return}const next=[...board];next[selected]=value;setBoard(next);setNotes(previous=>previous.map((values,i)=>i===selected?[]:values));setMessage(conflicts(next,size,selected,value)?'This digit conflicts with its row, column or box.':'Keep going — use Notes for possible digits.')}
  function hint(){if(won||!hints)return;const next=sudokuHint(puzzle,board,selected);if(!next)return;setHintCard(next);setSelected(next.index);setHints(value=>value-1);setMessage('Hint highlighted a cell. Read the explanation, then choose Fill it.')}
  function fillHint(){if(!hintCard||won)return;snapshot();setBoard(previous=>previous.map((value,i)=>i===hintCard.index?hintCard.value:value));setNotes(previous=>previous.map((values,i)=>i===hintCard.index?[]:values));setSelected(hintCard.index);setHintCard(null);setMessage('Hint applied. Continue with the next empty cell.')}
  function undo(){const last=history.at(-1);if(!last||won)return;setHintCard(null);setBoard(last.board);setNotes(last.notes);setHistory(previous=>previous.slice(0,-1));setMessage('Last move undone.')}
  function reset(){setHintCard(null);setBoard([...puzzle.givens]);setNotes(puzzle.givens.map(()=>[]));setHistory([]);setHints(3);setSeconds(0);setNoteMode(false);setMessage('This puzzle has been reset.')}
  return <section className="mini-sudoku panel"><div className="sudoku-heading"><div><div className="eyebrow">NUMBER · FREE PRACTICE</div><h1>Mini Sudoku {size}×{size}</h1><p>{difficulty} · Puzzle #{String(seed%10000).padStart(4,'0')}</p></div><div className="sudoku-badges"><span>◷ {String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</span><span>Hints {hints}</span></div></div>
    <div className="sudoku-settings"><label>Board size<select value={size} onChange={event=>start(Number(event.target.value))}>{[6,8,10].map(value=><option key={value} value={value}>{value}×{value}</option>)}</select></label><div role="group" aria-label="Difficulty">{(['Easy','Medium','Hard'] as Difficulty[]).map(value=><button key={value} className={difficulty===value?'':'secondary'} aria-pressed={difficulty===value} onClick={()=>{if(value!==difficulty)start(size,value)}}>{value}</button>)}</div></div>
    <div className="sudoku-board" role="group" aria-label="Sudoku board" style={{gridTemplateColumns:`repeat(${size},1fr)`}} onKeyDown={event=>{const index=selected,row=Math.floor(index/size),col=index%size;if(event.key.startsWith('Arrow')){event.preventDefault();setSelected(event.key==='ArrowLeft'?row*size+Math.max(0,col-1):event.key==='ArrowRight'?row*size+Math.min(size-1,col+1):event.key==='ArrowUp'?Math.max(0,row-1)*size+col:Math.min(size-1,row+1)*size+col)}else if(/^[1-9]$/.test(event.key)&&Number(event.key)<=size){event.preventDefault();enter(Number(event.key))}else if(event.key==='0'&&size===10){event.preventDefault();enter(10)}else if(['Delete','Backspace'].includes(event.key)){event.preventDefault();enter(0)}}}>
      {board.map((value,index)=>{const row=Math.floor(index/size),col=index%size,conflict=conflicts(board,size,index,value),related=Math.floor(selected/size)===row||selected%size===col||(Math.floor(Math.floor(selected/size)/2)===Math.floor(row/2)&&Math.floor((selected%size)/puzzle.boxCols)===Math.floor(col/puzzle.boxCols));return <button key={index} type="button" aria-label={`Row ${row+1}, column ${col+1}, ${value||'empty'}${puzzle.givens[index]?', fixed clue':''}`} aria-pressed={selected===index} className={`sudoku-cell ${puzzle.givens[index]?'given':''} ${selected===index?'selected':related?'related':''} ${conflict?'conflict':''} ${hintCard?.index===index?'hinted':''} ${col>0&&col%puzzle.boxCols===0?'box-left':''} ${row>0&&row%2===0?'box-top':''}`} onClick={()=>{setSelected(index);setHintCard(null)}}>{value||<span className="sudoku-notes" style={{gridTemplateColumns:`repeat(${puzzle.boxCols},1fr)`}}>{Array.from({length:size},(_,n)=><span key={n}>{notes[index].includes(n+1)?n+1:''}</span>)}</span>}</button>})}
    </div>
    <div className="sudoku-tools"><button className="secondary" aria-pressed={noteMode} onClick={()=>setNoteMode(value=>!value)}>✎ Notes {noteMode?'on':''}</button><button className="secondary" disabled={won||!!puzzle.givens[selected]} onClick={()=>enter(0)}>⌫ Clear</button><button className="secondary" disabled={!history.length||won} onClick={undo}>↶ Undo</button></div>
    <div className="sudoku-digits" style={{gridTemplateColumns:`repeat(${size/2},1fr)`}}>{Array.from({length:size},(_,n)=><button className="secondary" key={n} disabled={won} onClick={()=>enter(n+1)}>{n+1}</button>)}</div>
    <div className="sudoku-actions"><button onClick={()=>start()}>✧ New Puzzle</button><button className="secondary" disabled={!hints||won||!!hintCard} onClick={hint}>✧ Hint ({hints})</button><button className="secondary" onClick={reset}>↻ Reset</button></div>
    {hintCard&&<aside className="sudoku-hint-card" aria-live="polite"><span aria-hidden="true">♧</span><div><strong>Row {Math.floor(hintCard.index/size)+1}, column {hintCard.index%size+1}</strong><p>{hintCard.reason}</p></div><button onClick={fillHint}>Fill it</button><button className="secondary" aria-label="Dismiss hint" onClick={()=>setHintCard(null)}>×</button></aside>}
    <p role="status" className="sudoku-status">{won?`✓ Puzzle complete! ${Math.floor(seconds/60)}m ${seconds%60}s · ${3-hints} hints used.`:message}</p><p className="muted">Every row, column and {puzzle.boxRows}×{puzzle.boxCols} box must contain 1–{size}. Arrow keys move selection; 0 enters 10 on a 10×10 board. Practice results stay in this session.</p>
  </section>;
}
