import type {ReactNode} from 'react';
export const sections=['Overview','Users','Games','Challenges','Results','Content','Audit'] as const;
export const descriptions:Record<string,string>={Overview:'Your platform at a glance. Review activity and choose what needs attention.',Users:'Manage player access and trusted operators.',Games:'Tune ranked games, availability and instructions.',Challenges:'Schedule daily competitions and manage their lifecycle.',Results:'Review recorded attempts and keep rankings fair.',Content:'Keep your homepage, FAQ and contact information up to date.',Audit:'A traceable record of platform and account changes.'};
const paths:Record<string,ReactNode>={
 Overview:<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>,
 Users:<><circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m3 10v-3a6 6 0 0 0-3-5"/></>,
 Games:<><rect x="3" y="6" width="18" height="13" rx="4"/><path d="M7 10v5m-2-2.5h4m6-1h.01m3 3h.01"/></>,
 Challenges:<><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 5 3 3 5-5"/></>,
 Results:<><path d="M8 3h8v5a4 4 0 0 1-8 0V3zm4 9v6m-4 3h8M8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4"/></>,
 Content:<><path d="M14 3H5v18h14V8zm0 0v5h5M8 12h8m-8 4h5"/></>,
 Audit:<><path d="M9 5H5v16h14V5h-4M8 10h8m-8 4h8m-8 4h5"/><rect x="9" y="3" width="6" height="4" rx="1"/></>,
};
export function AdminIcon({name}:{name:string}){return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.Overview}</svg>}
export function Badge({value}:{value:string}){const tone=['Active','Available','published','validated','admin'].includes(value)?'positive':['Suspended','Unavailable','closed','invalidated'].includes(value)?'negative':value==='flagged'?'warning':'neutral';return <span className={`admin-badge ${tone}`}>{value}</span>}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="admin-empty"><AdminIcon name="Audit"/><h3>{title}</h3><p>{children}</p></div>}
export function AdminOverview({overview,recent,choose}:{overview:any;recent:any[];choose:(name:string)=>void}){
 const tiles=[['players','Players','Users'],['sessions','Game sessions','Results'],['validated','Validated results','Results'],['challenges','Daily challenges','Challenges']];
 return <><div className="admin-welcome"><div><span className="eyebrow">A GOOD PLACE TO START</span><h2>Keep the game running smoothly.</h2><p>Review players, prepare challenges and manage the moments that matter.</p><button onClick={()=>choose('Challenges')}>Manage challenges <span aria-hidden="true">↗</span></button></div><div className="admin-welcome-art" aria-hidden="true">{Array.from({length:9},(_,i)=><i className={[0,4,6].includes(i)?'signal':''} key={i}/>)}</div></div><div className="admin-metrics">{tiles.map(([key,label,target])=><button className="admin-metric" key={key} onClick={()=>choose(target)}><span className="metric-top"><span>{label}</span><AdminIcon name={target}/></span><strong>{overview[key]}</strong><span className="metric-bottom">View {target.toLowerCase()} <span aria-hidden="true">↗</span></span></button>)}</div><div className="admin-overview-grid"><div className="admin-surface"><div className="admin-block-heading"><h2>Review queue</h2><AdminIcon name="Results"/></div><p>Flagged attempts remain ranked until a reviewer invalidates them.</p><div className="admin-queue"><span>Flagged results</span><strong>{overview.flagged}</strong></div><div className="admin-queue"><span>Invalidated results</span><strong>{overview.invalidated}</strong></div><div className="admin-queue"><span>Active players</span><strong>{overview.activePlayers} / {overview.players}</strong></div><button className="secondary" onClick={()=>choose('Results')}>Review results →</button></div><div className="admin-surface"><div className="admin-block-heading"><h2>Recent changes</h2><button className="admin-text-button" onClick={()=>choose('Audit')}>View audit →</button></div>{recent.length?<div className="admin-activity">{recent.map(x=><div key={x.id}><span className="activity-icon"><AdminIcon name="Audit"/></span><div><strong>{x.action.replaceAll('.',' · ').replaceAll('_',' ')}</strong><p>{x.actor} · {new Date(x.created*1000).toLocaleString()}</p><span>{x.details.reason||x.target}</span></div></div>)}</div>:<Empty title="No changes recorded">Saved administrative changes will appear here.</Empty>}</div></div><div className="admin-footnote"><AdminIcon name="Audit"/><span>{overview.auditEntries} audit records · Every administrative change requires a reason.</span></div></>;
}
