import {useEffect,useRef,useState} from 'react';
import {api} from '../api/client';
import {AdminIcon,AdminOverview,Badge,Empty,sections,descriptions} from './AdminVisuals';
import './AdminPanel.css';
import {defaultGames} from '../games/catalog';
import {additionalPracticeGames} from '../games/practiceGames';
const practiceGames=[...defaultGames.filter(g=>'practiceOnly' in g&&g.practiceOnly),...additionalPracticeGames];
type Page={items:any[];total:number};
const empty:Page={items:[],total:0};
export default function AdminPanel(){
  const [tab,setTab]=useState('Overview'),[overview,setOverview]=useState<any>(null),[page,setPage]=useState<Page>(empty),[games,setGames]=useState<any[]>([]),[offset,setOffset]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[revision,setRevision]=useState(0);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[edit,setEdit]=useState<any>(null),[reason,setReason]=useState(''),[detail,setDetail]=useState<any>(null),[day,setDay]=useState(new Date().toISOString().slice(0,10)),[game,setGame]=useState('memory-grid');
  const [content,setContent]=useState<any>(null);
  const [recent,setRecent]=useState<any[]>([]),[search,setSearch]=useState(''),[draftReason,setDraftReason]=useState(''),[refreshed,setRefreshed]=useState('');
  const inFlight=useRef(false);
  useEffect(()=>{const timer=setTimeout(()=>setSearch(query),250);return()=>clearTimeout(timer)},[query]);
  const [loadFailed,setLoadFailed]=useState(false);
  useEffect(()=>{let active=true;setLoading(true);setLoadFailed(false);setError('');setPage(empty);
    const url=tab==='Overview'?'/admin/overview':tab==='Games'?'/admin/games':`/admin/${tab.toLowerCase()}?offset=${offset}&q=${encodeURIComponent(search)}${tab==='Results'?`&status=${filter}`:''}`;
    (tab==='Overview'?Promise.all([api(url),api('/admin/audit?limit=4')]).then(([stats,audit])=>{if(active)setRecent(audit.items);return stats}):api(url)).then(data=>{if(!active)return;setRefreshed(new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));if(tab==='Overview')setOverview(data);else if(tab==='Games')setGames(data);else if(tab==='Content')setContent(data);else setPage(data)}).catch(e=>{if(active){setError(e.message);setLoadFailed(true)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};
  },[tab,offset,search,filter,revision]);
  useEffect(()=>{if(edit||detail)document.getElementById('admin-editor')?.scrollIntoView({behavior:'smooth',block:'start'})},[!!edit,!!detail]);
  async function mutate(path:string,body:any){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');setNotice('');try{await api(path,body);setNotice('Saved. The audit history records this change.');setEdit(null);setDetail(null);setReason('');setDraftReason('');setRevision(r=>r+1)}catch(e){setError((e as Error).message)}finally{inFlight.current=false;setBusy(false)}}
  function choose(name:string){if(name===tab||inFlight.current)return;setLoading(true);setPage(empty);setTab(name);setOffset(0);setQuery('');setSearch('');setFilter('all');setEdit(null);setDetail(null);setReason('');setNotice('')}
  function select(value:any){if(inFlight.current)return;setEdit({...structuredClone(value),initialStatus:value.status});setReason('');setError('');setDetail(null)}
  async function inspect(id:string){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{setDetail(await api(`/admin/results/${id}`));setReason('')}catch(e){setError((e as Error).message)}finally{inFlight.current=false;setBusy(false)}}
  const validReason=reason.trim().length>=3;
  return <section className="admin admin-shell"><aside className="admin-sidebar"><div className="admin-sidebar-brand"><span className="admin-brand-mark"><AdminIcon name="Games"/></span><div><strong>Control room</strong><small>Belancer Game</small></div></div><span className="admin-nav-label">WORKSPACE</span><div className="admin-nav" role="tablist" aria-label="Admin sections">{sections.map(name=><button role="tab" aria-selected={tab===name} aria-controls="admin-workspace" className={tab===name?'selected':''} disabled={busy} key={name} onClick={()=>choose(name)}><AdminIcon name={name}/><span>{name}</span>{tab===name&&<i aria-hidden="true"/>}</button>)}</div><div className="admin-sidebar-note"><AdminIcon name="Audit"/><p>Thoughtful decisions.<br/>Traceable changes.</p><a href="/dashboard">Player dashboard ↗</a></div></aside><div className="admin-workspace" id="admin-workspace" role="tabpanel" aria-label={tab}><div className="admin-page-heading"><div><div className="eyebrow">BELANCER / ADMINISTRATION</div><h1>{tab==='Overview'?'Platform overview':tab}</h1><p>{descriptions[tab]}</p></div><button className="secondary admin-refresh" disabled={busy||loading} onClick={()=>setRevision(r=>r+1)}>Refresh data ↻</button></div><div className="admin-context"><span>{loading?'Updating…':loadFailed?'Unable to connect':`Updated at ${refreshed}`}</span><span>Daily boundaries · UTC</span></div>
      {['Users','Results'].includes(tab)&&<div className="admin-toolbar admin-search"><label>Search username<input maxLength={100} disabled={busy} value={query} onChange={e=>{setOffset(0);setQuery(e.target.value)}} placeholder="Search players"/></label>{tab==='Results'&&<label>Result status<select disabled={busy} value={filter} onChange={e=>{setOffset(0);setFilter(e.target.value)}}>{['all','validated','flagged','invalidated'].map(x=><option key={x}>{x}</option>)}</select></label>}</div>}
    {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}
    {loading?<div className="admin-loading" role="status"><span className="admin-spinner"/>Loading {tab.toLowerCase()}…</div>:loadFailed?<div><p>Unable to load this section. Sign in with an admin account or check the backend connection.</p><button className="secondary" onClick={()=>setRevision(r=>r+1)}>Retry loading</button></div>:<>
      {tab==='Overview'&&overview&&<AdminOverview overview={overview} recent={recent} choose={choose}/>}
      {tab==='Content'&&content&&<form className="panel admin-editor" onSubmit={e=>{e.preventDefault();void mutate('/admin/content',{...content,reason})}}><h2>Homepage, FAQ and contact</h2><label>Homepage headline<textarea required maxLength={120} value={content.headline} onChange={e=>setContent({...content,headline:e.target.value})}/></label><label>Homepage description<textarea required maxLength={500} value={content.description} onChange={e=>setContent({...content,description:e.target.value})}/></label><label>Contact information<textarea required maxLength={1000} value={content.contact} onChange={e=>setContent({...content,contact:e.target.value})}/></label><h3>Frequently asked questions</h3>{content.faq.map((f:any,i:number)=><div className="panel" key={i}><label>Question {i+1}<input required maxLength={200} value={f.question} onChange={e=>setContent({...content,faq:content.faq.map((x:any,j:number)=>i===j?{...x,question:e.target.value}:x)})}/></label><label>Answer<textarea required maxLength={1000} value={f.answer} onChange={e=>setContent({...content,faq:content.faq.map((x:any,j:number)=>i===j?{...x,answer:e.target.value}:x)})}/></label><button type="button" className="small secondary" disabled={content.faq.length<=1} onClick={()=>setContent({...content,faq:content.faq.filter((_:any,j:number)=>i!==j)})}>Remove question</button></div>)}<button type="button" className="secondary small" disabled={content.faq.length>=20} onClick={()=>setContent({...content,faq:[...content.faq,{question:'',answer:''}]})}>Add question</button><label>Reason<input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!validReason}>Save content</button></form>}

      {tab==='Users'&&<div className="table-wrap"><table><thead><tr><th>Username</th><th>Role</th><th>Status</th><th>Manage</th></tr></thead><tbody>{page.items.map(u=><tr key={u.id}><td>{u.username}</td><td><Badge value={u.role}/></td><td><Badge value={u.active?'Active':'Suspended'}/></td><td><button className="small secondary" disabled={busy} onClick={()=>select(u)}>Manage {u.username}</button></td></tr>)}</tbody></table></div>}
      {tab==='Games'&&<><div className="panel"><strong>{games.length+practiceGames.length} games in your catalog</strong><p>{games.length} ranked games with backend settings · {practiceGames.length} local practice games.</p></div><h2>Ranked games</h2><p>Defaults apply to newly generated daily challenges. Published and existing draft challenge content stays fixed. Game availability controls new sessions; existing attempts can finish.</p><div className="challenge-list admin-game-list">{games.map(g=><div className="panel" key={g.slug}><span className="tag">{g.category} · {g.available?'Available':'Unavailable'}</span><h2>{g.name}</h2><p>{g.description}</p><p>{g.configuration.durationSeconds}s · {g.configuration.rounds?`${g.configuration.rounds} rounds`:'8 pairs'}</p><button className="secondary" disabled={busy} onClick={()=>select(g)}>Edit {g.name}</button></div>)}</div><h2>Practice games</h2><p>These games run locally in the browser. Scores do not enter ranked leaderboards. Practice rules are maintained in the codebase.</p><div className="challenge-list admin-game-list">{practiceGames.map(g=><div className="panel" key={g.slug}><div className="admin-game-heading"><span className="admin-game-icon" aria-hidden="true">{g.icon}</span><Badge value="Practice only"/></div><span className="tag">{g.category}</span><h2>{g.name}</h2><p>{g.description}</p><a className="button secondary" href={`/games/${g.slug}`}>View {g.name} ↗</a></div>)}</div></>}
      {tab==='Challenges'&&<><form className="panel admin-toolbar" onSubmit={e=>{e.preventDefault();void mutate('/admin/challenges',{game,day,reason:draftReason})}}><label>Game<select value={game} onChange={e=>setGame(e.target.value)}>{['memory-grid','pair-finder','quick-match','focus-finder','math-sprint'].map(x=><option key={x}>{x}</option>)}</select></label><label>Date (UTC)<input type="date" min={new Date().toISOString().slice(0,10)} value={day} onChange={e=>setDay(e.target.value)} required/></label><label>Draft reason<input value={draftReason} minLength={3} maxLength={500} onChange={e=>setDraftReason(e.target.value)} required/></label><button disabled={busy||draftReason.trim().length<3}>Create draft</button></form><p>Publish a draft to allow starts on its date. Closing stops new attempts; sessions already started can finish. Today’s unpublished games are created automatically on first play unless a draft exists.</p><div className="table-wrap"><table><thead><tr><th>Date</th><th>Game</th><th>Status</th><th>Rules</th><th>Manage</th></tr></thead><tbody>{page.items.map(c=><tr key={c.id}><td>{c.day}</td><td>{c.game}</td><td><Badge value={c.status}/></td><td>{c.configuration.durationSeconds}s · {c.configuration.rounds||'8 pairs'}</td><td><button className="small secondary" disabled={busy} onClick={()=>select(c)}>Manage challenge</button></td></tr>)}</tbody></table></div></>}
      {tab==='Results'&&<div className="table-wrap"><table><thead><tr><th>Player</th><th>Game</th><th>Score</th><th>Status</th><th>Review</th></tr></thead><tbody>{page.items.map(r=><tr key={r.session}><td>{r.username}</td><td>{r.game}</td><td>{r.score}</td><td><Badge value={r.status}/>{r.flagged&&<Badge value="flagged"/>}</td><td><button disabled={busy} className="small secondary" onClick={()=>inspect(r.session)}>Review result</button></td></tr>)}</tbody></table></div>}
      {tab==='Audit'&&<div className="table-wrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Details</th></tr></thead><tbody>{page.items.map(x=><tr key={x.id}><td>{new Date(x.created*1000).toLocaleString()}</td><td>{x.actor}</td><td>{x.action}</td><td><details><summary>{x.details.reason||x.target}</summary><pre>{JSON.stringify(x.details,null,2)}</pre></details></td></tr>)}</tbody></table></div>}
      {!['Overview','Games','Content'].includes(tab)&&<div className="admin-pagination"><button className="secondary small" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous</button><span>{page.total?`${offset+1}–${Math.min(offset+20,page.total)} of ${page.total}`:'No records'}</span><button className="secondary small" disabled={busy||offset+20>=page.total} onClick={()=>setOffset(offset+20)}>Next</button></div>}
    </>}
    {!loading&&!loadFailed&&edit&&<form id="admin-editor" className="panel admin-editor" onSubmit={e=>{e.preventDefault();if(tab==='Users')void mutate(`/admin/users/${edit.id}`,{role:edit.role,active:edit.active,reason});else if(tab==='Games'){const {name,description,instructions,available,configuration}=edit;void mutate(`/admin/games/${edit.slug}`,{name,description,instructions,available,configuration,reason})}else void mutate(`/admin/challenges/${encodeURIComponent(edit.id)}`,{status:edit.status,reason})}}>
      <h2>{tab==='Users'?`Manage ${edit.username}`:tab==='Games'?`Edit ${edit.name}`:`Manage ${edit.game} · ${edit.day}`}</h2>
      {tab==='Users'&&<><label>Role<select value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}><option>player</option><option>admin</option></select></label><label className="check"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Account active</label><p>Suspension signs this user out and removes them from rankings. Self-suspension and self-demotion are blocked.</p></>}
      {tab==='Games'&&<><label>Name<input value={edit.name} required maxLength={80} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Description<textarea value={edit.description} required maxLength={500} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label>Additional instructions<textarea value={edit.instructions} maxLength={2000} onChange={e=>setEdit({...edit,instructions:e.target.value})}/></label><label className="check"><input type="checkbox" checked={edit.available} onChange={e=>setEdit({...edit,available:e.target.checked})}/> Available to players</label><div className="admin-toolbar">{Object.entries(edit.configuration).map(([key,value])=><label key={key}>{{durationSeconds:"Time limit (seconds)",rounds:"Rounds / questions",cells:"Memory cells"}[key as "durationSeconds"|"rounds"|"cells"]||key}<input type="number" min={key==='durationSeconds'?10:key==='cells'?3:1} max={key==='durationSeconds'?600:key==='cells'?8:edit.slug==='memory-grid'?10:edit.slug==='focus-finder'?50:120} step="1" value={String(value)} required onChange={e=>setEdit({...edit,configuration:{...edit.configuration,[key]:Number(e.target.value)}})}/></label>)}</div><h2>Practice games</h2><p>These games run locally in the browser. Scores do not enter ranked leaderboards. Practice rules are maintained in the codebase.</p><div className="challenge-list admin-game-list">{practiceGames.map(g=><div className="panel" key={g.slug}><div className="admin-game-heading"><span className="admin-game-icon" aria-hidden="true">{g.icon}</span><Badge value="Practice only"/></div><span className="tag">{g.category}</span><h2>{g.name}</h2><p>{g.description}</p><a className="button secondary" href={`/games/${g.slug}`}>View {g.name} ↗</a></div>)}</div></>}
      {tab==='Challenges'&&<><p>Content and configuration are fixed when the draft is created. Published challenges cannot return to draft; closed challenges cannot reopen.</p><label>Status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option disabled={edit.initialStatus!=='draft'}>draft</option><option disabled={edit.initialStatus==='closed'}>published</option><option>closed</option></select></label></>}
      <label>Reason for this change<input value={reason} minLength={3} maxLength={500} onChange={e=>setReason(e.target.value)} required/></label><div className="actions"><button disabled={busy||!validReason}>{busy?'Saving…':'Save changes'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></div>
    </form>}
    {!loading&&!loadFailed&&detail&&<div id="admin-editor" className="panel admin-editor"><h2>Review {detail.username} · {detail.result.game}</h2><p>{detail.result.score} points · {detail.result.accuracy}% accuracy · {detail.result.status}{detail.result.flagged?' · flagged':''}</p>{detail.result.invalidationReason&&<p>Invalidation: {detail.result.invalidationReason}</p>}<details><summary>Inspect {detail.events.length} recorded actions</summary><pre>{JSON.stringify(detail.events,null,2)}</pre></details><label>Review reason<input value={reason} minLength={3} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><div className="actions">{[detail.result.flagged?'clear_flag':'flag',detail.result.status==='invalidated'?'restore':'invalidate'].map(action=><button className={action==='invalidate'?'danger':'secondary'} key={action} disabled={busy||!validReason} onClick={()=>mutate(`/admin/results/${detail.result.session}`,{action,reason})}>{action.replace('_',' ')}</button>)}<button className="secondary" onClick={()=>setDetail(null)}>Close review</button></div><p>Invalidation removes this attempt from rankings. The player’s next best valid attempt can take its place. Scores are preserved for audit.</p></div>}
  </div></section>;
}
