import {useEffect,useState} from 'react';
import {api} from '../api/client';
export default function Leaderboards({games}:{games:any[]}){
 const [game,setGame]=useState(new URLSearchParams(location.search).get('game')||'memory-grid'),[period,setPeriod]=useState('daily'),[day,setDay]=useState(new Date().toISOString().slice(0,10)),[rules,setRules]=useState(''),[offset,setOffset]=useState(0),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;setLoading(true);setError('');api(`/standings/${encodeURIComponent(game)}?period=${period}&day=${day}&rules=${rules}&offset=${offset}`).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[game,period,day,rules,offset]);
 function change(setter:(v:string)=>void,value:string){setter(value);setRules('');setOffset(0)}
 function label(c:any){return `${c.durationSeconds}s${c.rounds?` · ${c.rounds} rounds`:''}${c.cells?` · ${c.cells} cells`:''}`}
 return <section><div className="eyebrow">THE STANDINGS · UTC · RULES V2</div><h1>A little friendly competition.</h1><div className="admin-toolbar"><label>Game<select value={game} onChange={e=>change(setGame,e.target.value)}>{games.map(g=><option key={g.slug} value={g.slug}>{g.name}</option>)}</select></label><label>Period<select value={period} onChange={e=>change(setPeriod,e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="all-time">All time</option></select></label><label>{period==='daily'?'Challenge date':period==='weekly'?'Date within week':'Through date'}<input type="date" value={day} max={new Date().toISOString().slice(0,10)} required onChange={e=>{if(e.target.value)change(setDay,e.target.value)}}/></label></div><p>Your best validated attempt in the selected period counts. Weekly periods start Monday UTC. Different timing, round and cell settings have separate boards. <a href="/competition-rules">Ranking rules →</a></p>{error?<p className="error" role="alert">{error}</p>:loading?<p role="status">Loading standings…</p>:data&&<><label>Challenge settings<select value={data.rules} onChange={e=>{setRules(e.target.value);setOffset(0)}}>{data.profiles.map((p:any)=><option key={p.id} value={p.id}>{label(p.configuration)}</option>)}</select></label><p>{data.start?`${data.start} through ${new Date(Date.parse(data.endExclusive)-86400000).toISOString().slice(0,10)}`:`All recorded challenges through ${data.day}`} · {data.total} players{data.yourRank?` · Your rank: #${data.yourRank}`:''}</p><p>Daily puzzles can vary in difficulty even with matching settings. These boards show recorded game performance, with no prizes.</p>{data.items.length?<div className="table-wrap"><table><thead><tr><th>Rank</th><th>Player</th><th>Score</th><th>Accuracy</th><th>Time</th><th>Challenge</th></tr></thead><tbody>{data.items.map((r:any)=><tr key={r.username} className={r.isYou?'you':''}><td>#{r.rank}</td><td>{r.username}{r.isYou?' · you':''}</td><td>{r.score}</td><td>{r.accuracy}%</td><td>{(r.duration/1000).toFixed(1)}s</td><td>{r.challenge.split(':')[0]} · {r.completed?'complete':'partial'}</td></tr>)}</tbody></table></div>:<div className="panel"><h2>The board is open.</h2><p>No validated results for this period and challenge setting.</p><a href={`/challenges/${game}`} className="button">Play today's challenge</a></div>}<div className="admin-pagination"><button className="secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-20))}>Previous</button><span>{data.total?offset+1:0}–{Math.min(offset+20,data.total)} of {data.total}</span><button className="secondary" disabled={offset+20>=data.total} onClick={()=>setOffset(offset+20)}>Next</button></div></>}</section>
}
