import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api} from './api/client';
import GamePlayer from './game-shell/GamePlayer';
import TicTacToe from './game-shell/TicTacToe';
import ExtraPracticeGames from './game-shell/ExtraPracticeGames';
import AdditionalPracticeGame from './game-shell/AdditionalPracticeGame';
import ThemeToggle from './components/ThemeToggle';
import AdminPanel from './pages/AdminPanel';
import AccountSettings from './pages/AccountSettings';
import Progress from './pages/Progress';
import Leaderboards from './pages/Leaderboards';
import GamesCatalog from './pages/GamesCatalog';
import BrainGamesInfo from './pages/BrainGamesInfo';
import {additionalPracticeGames} from './games/practiceGames';
import '@fontsource-variable/manrope';
import '@fontsource-variable/dm-sans/wght.css';
import './styles.css';
import './typography.css';
import {defaultGames} from './games/catalog';
function App(){
 const [games,setGames]=useState<any[]>([...defaultGames,...additionalPracticeGames]),[content,setContent]=useState<any>({headline:'A little sharper.\nA little every day.',description:'Give your curiosity a place to play with quick games across memory, focus, problem solving and more.',contact:'Contact details must be supplied by the deployment operator before public release.',faq:[]});
 const path=location.pathname,[user,setUser]=useState<any>(null),[error,setError]=useState(''),[challenges,setChallenges]=useState<any[]>([]);
 useEffect(()=>{api('/content').then(setContent).catch(()=>{});api('/games').then(list=>setGames([...list.map((g:any)=>({...defaultGames.find(d=>d.slug===g.slug),...g})),...defaultGames.filter(g=>g.practiceOnly&&!list.some((item:any)=>item.slug===g.slug)),...additionalPracticeGames])).catch(e=>setError(e.message));if(path==='/challenges'||path.startsWith('/challenges/'))api('/challenges').then(setChallenges).catch(e=>setError(e.message));api('/auth/me').then(setUser).catch(()=>{})},[]);
 const slug=path.split('/')[2],game=games.find(g=>g.slug===slug);
 async function auth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const data=new FormData(e.currentTarget);try{await api(`/auth/${path==='/signup'?'register':'login'}`,{username:data.get('username'),password:data.get('password')});location.href='/dashboard'}catch(e){setError((e as Error).message)}}
 return <><header><div className="header-inner"><a className="brand" href="/" aria-label="Belancer Game"><img className="brand-logo" src="/belancer-logo.png" alt=""/><span className="brand-game">game</span></a><nav><a href="/games">Games</a><a href="/challenges">Challenges</a><a href="/leaderboards">Leaderboards</a></nav><div className="account"><ThemeToggle/>{user?<><a className="account-profile" href="/dashboard"><span className="account-avatar" aria-hidden="true">{String(user.username||'?').charAt(0).toUpperCase()}</span><span>{user.username}</span></a>{user.role==='admin'&&<a href="/admin">Admin</a>}<button className="small secondary" onClick={async()=>{await api('/auth/logout',{});location.href='/'}}>Log out</button></>:<><a href="/login">Log in</a><a className="button small" href="/signup">Join free ↗</a></>}</div></div></header>
 <main>{path==='/login'&&new URLSearchParams(location.search).has('passwordChanged')&&<p role="status">Password changed. Sign in with your new password.</p>}{error&&<div className="error" role="alert">{error}</div>}
 {path==='/'&&<><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> YOUR DAILY DOSE OF DISCOVERY</div><h1>{content.headline.split("\n").map((line:string,i:number)=><React.Fragment key={i}>{i>0&&<br/>}{i>0?<em>{line}</em>:line}</React.Fragment>)}</h1><p>{content.description}</p><div className="actions"><a className="button" href="/games">Find your first game ↗</a><a href="/how-it-works">How it works →</a></div><div className="hero-stats"><div><strong>{games.length}</strong><span>games to explore</span></div><div><strong>{games.filter(g=>!g.practiceOnly).length}</strong><span>daily challenge games</span></div><div><strong>{new Set(games.map(g=>g.category)).size}</strong><span>skill areas</span></div><div><strong>Free</strong><span>practice available</span></div></div></div></section>
 <GamesCatalog games={games} key="home-catalog"/>
 <section className="challenge-banner"><div><div className="eyebrow">A FRESH START, EVERY DAY</div><h2>Your next challenge is waiting.</h2><p>Same rules. Three attempts. See where you stand.</p></div><a className="button" href="/challenges">Explore daily challenges ↗</a></section><section className="how"><div className="eyebrow">SIMPLE BY DESIGN</div><h2>Choose. Play. Discover.</h2><div className="steps">{['Pick a game that sparks your curiosity.','Take a few minutes to challenge yourself.','Review your result and try a daily challenge.'].map((s,i)=><div key={s}><span>0{i+1}</span><p>{s}</p></div>)}</div></section><BrainGamesInfo faq={content.faq}/></>}
 {(path==='/games'||path.startsWith('/games/category/'))&&<GamesCatalog games={games} key={slug||'all'}/>}
 {path.startsWith('/games/')&&!path.startsWith('/games/category/')&&game&&<section className="panel game-detail"><div className="game-art" style={{background:game.color,color:game.ink}}>{game.icon}</div><span className="tag">{game.category}{game.practiceOnly?' · FREE PRACTICE':''}</span><h1>{game.name}</h1><p>{game.description}</p>{game.instructions&&<p>{game.instructions}</p>}{game.available===false&&<p>This game is currently unavailable.</p>}{game.practiceOnly&&<p>This is a local practice game; scores are not saved to leaderboards.</p>}<p>Learn the controls in free practice{game.practiceOnly?'':' then compete in today’s challenge'}.</p>{game.available!==false&&<div className="actions"><a className="button" href={`/play/${game.slug}`}>Start practice</a>{!game.practiceOnly&&<a className="button secondary" href={`/challenges/${game.slug}`}>Daily challenge</a>}</div>}</section>}
 {(path.startsWith('/play/')||path.startsWith('/challenges/'))&&game&&(path.startsWith('/challenges/')&&game.practiceOnly?<section className="panel game-detail"><h1>{game.name}</h1><p>This game is available for free practice only; ranked challenges aren’t supported.</p><a className="button" href={`/play/${game.slug}`}>Start practice</a></section>:game.slug==='tic-tac-toe'?<TicTacToe/>:['sequence-recall','color-match','odd-one-out','word-scramble'].includes(game.slug)?<ExtraPracticeGames key={game.slug} mode={game.slug as 'sequence-recall'|'color-match'|'odd-one-out'|'word-scramble'}/>:additionalPracticeGames.some(item=>item.slug===game.slug)?<AdditionalPracticeGame key={game.slug} slug={game.slug} name={game.name}/>:<GamePlayer game={game.slug} ranked={path.startsWith('/challenges/')} instructions={path.startsWith('/challenges/')?challenges.find(c=>c.slug===game.slug)?.instructions:game.instructions} configuration={challenges.find(c=>c.slug===game.slug)?.configuration} canStart={game.available!==false&&(!path.startsWith('/challenges/')||challenges.find(c=>c.slug===game.slug)?.status==='published')}/>)}
 {path==='/challenges'&&<section className="challenge-page"><div className="catalog-intro"><div className="eyebrow">TODAY'S LINEUP · UTC</div><h1>Rise to the challenge.</h1><p>Choose a ranked game, check your attempts, and see how you do.</p></div><div className="challenge-note"><strong>Three attempts per game, each day.</strong><span>Started and interrupted sessions count toward the limit. Challenges reset at midnight UTC.</span><a href="/competition-rules">Read the competition rules →</a></div><div className="challenge-grid">{games.filter(g=>!g.practiceOnly).map(g=>{const challenge=challenges.find(c=>c.slug===g.slug);const isOpen=g.available!==false&&challenge?.status==='published';return <article className="challenge-card" key={g.slug}><div className="catalog-art" style={{background:g.color,color:g.ink}} aria-hidden="true"><span className="catalog-art-mark">{g.icon}</span><span className="catalog-art-spark">✦</span></div><div className="catalog-copy"><span className="tag">{g.category} · DAILY CHALLENGE</span><h2>{g.name}</h2><p className="challenge-config">{challenge?.configuration?.durationSeconds?`${challenge.configuration.durationSeconds} seconds`:g.slug==='pair-finder'?'8 pairs':'Challenge rules'}{challenge?.configuration?.rounds?` · ${challenge.configuration.rounds} rounds`:''}</p><p className="challenge-attempts">{challenge?.attemptsRemaining==null?'Sign in to see remaining attempts':`${challenge.attemptsRemaining} of 3 attempts remaining`} · Rules v2</p>{isOpen?<a className="catalog-play" href={`/challenges/${g.slug}`}>Enter challenge <span aria-hidden="true">↗</span></a>:<span className="challenge-status">{g.available===false?'Game unavailable':challenge?.status||'Loading challenge…'}</span>}</div></article>})}</div></section>}
 {['/login','/signup'].includes(path)&&<section className="panel auth"><div className="eyebrow">YOUR NEXT CHAPTER</div><h1>{path==='/signup'?'Join the game.':'Welcome back.'}</h1><form onSubmit={auth}><label>Username<input name="username" pattern="[a-zA-Z0-9_]+" minLength={3} maxLength={24} required autoComplete="username"/></label><label>Password<input name="password" type="password" minLength={8} maxLength={128} required autoComplete={path==='/signup'?'new-password':'current-password'}/></label><button>{path==='/signup'?'Create account':'Log in'}</button></form><p><a href={path==='/signup'?'/login':'/signup'}>{path==='/signup'?'Already a member? Log in':'New here? Join free'}</a></p></section>}
 {['/dashboard','/progress'].includes(path)&&<Progress/>}
 {path==='/settings'&&<AccountSettings/>}
 {path==='/leaderboards'&&<Leaderboards games={games.filter(g=>!g.practiceOnly)}/>}
 {path==='/admin'&&<AdminPanel/>}
 {['/how-it-works','/competition-rules','/privacy','/terms','/contact','/forgot-password'].includes(path)&&<section className="panel prose"><h1>{path.slice(1).replaceAll('-',' ')}</h1>{path==='/competition-rules'?<><p>Daily challenges reset at midnight UTC. Starting a session consumes one of three attempts. Game-specific server time limits; no pause. Published challenge cards and instructions show the fixed timing and round configuration. Admin defaults apply only when a new challenge is generated. Your best validated result counts.</p><p>Speed, Attention and Math: score descending, accuracy descending, submission time ascending. Memory: complete correct patterns descending, incorrect cells ascending, answer response time ascending. Required two-second pattern displays are excluded from response time. Pairs: completed first, duration ascending, moves ascending; unfinished games compare pairs found.</p><p>Rules v2. Suspended players and invalidated attempts are excluded from rankings. Everyone receives the same daily challenge content; repeated attempts can become familiar. Your best valid attempt counts. Older versions have separate rankings. Weekly boards start Monday UTC; all-time boards include challenges through the chosen date. Both use one best validated attempt per player and separate challenge configuration profiles. Matching settings do not guarantee identical puzzle difficulty. Resume a ranked session on the same browser after refresh; its timer keeps running. At timeout, answered rounds or found pairs count. Rankings can be affected by network latency. No prizes.</p></>:path==='/how-it-works'?<p>Choose a game, read the instructions, and practice for free. Sign in to play daily challenges. The server evaluates your answers before adding your result to the leaderboard.</p>:path==='/privacy'?<p>Demo notice: the service stores usernames, password hashes, login sessions, challenge attempts and results. Daily leaderboards display usernames. Do not use sensitive personal information. Production requires a published retention and deletion policy.</p>:path==='/terms'?<p>This is a demonstration platform. Game scores describe performance, not health or intelligence. Play fairly. Production terms must be reviewed before public release.</p>:path==='/settings'?<p>Keyboard and touch controls are supported. The demo has no audio. Language and account editing are planned.</p>:path==='/forgot-password'?<p>Password recovery is not configured in this demo. Contact the operator of your deployment for account assistance.</p>:<p>{content.contact}</p>}</section>}
 {!['/','/games','/challenges','/signup','/login','/dashboard','/progress','/leaderboards','/admin','/how-it-works','/competition-rules','/privacy','/terms','/contact','/settings','/forgot-password'].includes(path)&&!game&&!path.startsWith('/games/category/')&&<section><h1>Page not found.</h1><a href="/games">Explore games →</a></section>}
 </main><footer className="site-footer"><div className="footer-inner"><div className="footer-columns"><div className="footer-brand-column"><a className="brand" href="/" aria-label="Belancer Game"><img className="brand-logo" src="/belancer-logo.png" alt=""/><span className="brand-game">game</span></a><p>A little time for your mind.</p></div><nav className="footer-links" aria-label="Explore"><h2>Explore</h2><a href="/games">All games</a><a href="/challenges">Daily challenges</a><a href="/leaderboards">Leaderboards</a><a href="/progress">Your progress</a></nav><nav className="footer-links" aria-label="About"><h2>About</h2><a href="/how-it-works">How it works</a><a href="/competition-rules">Competition rules</a><a href="/contact">Contact</a></nav><nav className="footer-links" aria-label="Legal"><h2>Legal</h2><a href="/privacy">Privacy</a><a href="/terms">Terms of service</a></nav></div><div className="footer-bottom"><p>Brain games · Daily challenges · Play at your pace</p><small>© {new Date().getFullYear()} Belancer Game · Demo release</small></div></div></footer></>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
