import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api} from './api/client';
import GamePlayer from './game-shell/GamePlayer';
import AdminPanel from './pages/AdminPanel';
import AccountSettings from './pages/AccountSettings';
import Progress from './pages/Progress';
import './styles.css';
const defaultGames=[{slug:'memory-grid',name:'Memory Grid',category:'Memory',icon:'▦',description:'A fleeting pattern. A lasting impression.',color:'#8067ec'},{slug:'pair-finder',name:'Pair Finder',category:'Memory',icon:'◈',description:'Make connections, one pair at a time.',color:'#df9b45'},{slug:'quick-match',name:'Quick Match',category:'Speed',icon:'ϟ',description:'Trust your eyes. Beat your hesitation.',color:'#e87b7b'},{slug:'focus-finder',name:'Focus Finder',category:'Attention',icon:'◎',description:'Find the detail that makes a difference.',color:'#459b96'},{slug:'math-sprint',name:'Math Sprint',category:'Math',icon:'∑',description:'Small sums. Big momentum.',color:'#6a90cb'}];
function App(){
 const [games,setGames]=useState<any[]>(defaultGames),[content,setContent]=useState<any>({headline:'A little sharper.\nA little every day.',description:'Give your curiosity a place to play. Five quick games to challenge your memory, focus, and thinking.',contact:'Contact details must be supplied by the deployment operator before public release.',faq:[]});
 const path=location.pathname,[user,setUser]=useState<any>(null),[error,setError]=useState(''),[category,setCategory]=useState('All'),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState(new URLSearchParams(location.search).get('game')||'memory-grid'),[challenges,setChallenges]=useState<any[]>([]);
 useEffect(()=>{api('/content').then(setContent).catch(()=>{});api('/games').then(list=>setGames(list.map((g:any)=>({...defaultGames.find(d=>d.slug===g.slug),...g})))).catch(e=>setError(e.message));if(path==='/challenges'||path.startsWith('/challenges/'))api('/challenges').then(setChallenges).catch(e=>setError(e.message));api('/auth/me').then(setUser).catch(()=>{})},[]);
 useEffect(()=>{if(path==='/leaderboards')api(`/leaderboards/${selected}`).then(setRows).catch(e=>setError(e.message))},[selected]);
 const slug=path.split('/')[2],game=games.find(g=>g.slug===slug);
 async function auth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const data=new FormData(e.currentTarget);try{await api(`/auth/${path==='/signup'?'register':'login'}`,{username:data.get('username'),password:data.get('password')});location.href='/dashboard'}catch(e){setError((e as Error).message)}}
 function cards(list=games){return <div className="cards">{list.filter(g=>g.available!==false).map(g=><a href={`/games/${g.slug}`} className="game-card" key={g.slug}><div className="game-art" style={{background:g.color}}><span>{g.icon}</span><div className="art-dots">• • •</div></div><div className="card-copy"><span className="tag">{g.category}</span><h3>{g.name}</h3><p>{g.description}</p><span className="card-link">Explore game ↗</span></div></a>)}</div>}
 return <><header><a className="brand" href="/"><span className="brand-icon">b.</span>belancer<span className="brand-game">game</span></a><nav><a href="/games">Games</a><a href="/challenges">Challenges</a><a href="/leaderboards">Leaderboards</a></nav><div className="account">{user?<><a href="/dashboard">{user.username}</a>{user.role==='admin'&&<a href="/admin">Admin</a>}<button className="small secondary" onClick={async()=>{await api('/auth/logout',{});location.href='/'}}>Log out</button></>:<><a href="/login">Log in</a><a className="button small" href="/signup">Join free ↗</a></>}</div></header>
 <main>{path==='/login'&&new URLSearchParams(location.search).has('passwordChanged')&&<p role="status">Password changed. Sign in with your new password.</p>}{error&&<div className="error" role="alert">{error}</div>}
 {path==='/'&&<><section className="hero"><div><div className="eyebrow"><span className="status-dot"/> YOUR DAILY DOSE OF DISCOVERY</div><h1>{content.headline.split("\n").map((line:string,i:number)=><React.Fragment key={i}>{i>0&&<br/>}{i>0?<em>{line}</em>:line}</React.Fragment>)}</h1><p>{content.description}</p><div className="actions"><a className="button" href="/games">Find your first game ↗</a><a href="/how-it-works">How it works →</a></div><div className="hero-note">5 original games <span>·</span> Free practice <span>·</span> Play at your pace</div></div><a href="/games/memory-grid" className="hero-art"><div className="floating-label">MEMORY GRID <span>↗</span></div><div className="preview-grid">{Array.from({length:16},(_,i)=><div key={i} className={[1,6,8,11,14].includes(i)?'active':''}>{[1,6,8,11,14].includes(i)?'✦':''}</div>)}</div><div className="art-caption">A moment to remember.</div></a></section>
 <section><div className="section-heading"><div><div className="eyebrow">FIND YOUR FLOW</div><h2>What will you challenge today?</h2></div><a href="/games">View all games ↗</a></div><div className="filters">{['All','Memory','Speed','Attention','Math'].map(c=><button className={category===c?'chosen':'secondary'} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div>{cards(games.filter(g=>category==='All'||g.category===category))}</section>
 <section className="challenge-banner"><div><div className="eyebrow">A FRESH START, EVERY DAY</div><h2>Your next challenge is waiting.</h2><p>Same rules. Three attempts. See where you stand.</p></div><a className="button" href="/challenges">Explore daily challenges ↗</a></section><section className="how"><div className="eyebrow">SIMPLE BY DESIGN</div><h2>Choose. Play. Discover.</h2><div className="steps">{['Pick a game that sparks your curiosity.','Take a few minutes to challenge yourself.','Review your result and try a daily challenge.'].map((s,i)=><div key={s}><span>0{i+1}</span><p>{s}</p></div>)}</div></section><section className="faq"><h2>A few things to know</h2>{content.faq.map((f:any,i:number)=><details key={i}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</section></>}
 {(path==='/games'||path.startsWith('/games/category/'))&&<section><div className="eyebrow">A PLACE TO PLAY</div><h1>Find your next favorite.</h1><div className="filters">{['All','Memory','Speed','Attention','Math'].map(c=><button key={c} className={category===c?'chosen':'secondary'} onClick={()=>setCategory(c)}>{c}</button>)}</div>{cards(games.filter(g=>(path.startsWith('/games/category/')?g.category.toLowerCase()===slug:category==='All'||g.category===category)))}</section>}
 {path.startsWith('/games/')&&!path.startsWith('/games/category/')&&game&&<section className="panel game-detail"><div className="game-art" style={{background:game.color}}>{game.icon}</div><span className="tag">{game.category}</span><h1>{game.name}</h1><p>{game.description}</p>{game.instructions&&<p>{game.instructions}</p>}{game.available===false&&<p>This game is currently unavailable.</p>}<p>Learn the controls in free practice, then compete in today's challenge.</p>{game.available!==false&&<div className="actions"><a className="button" href={`/play/${game.slug}`}>Start practice</a><a className="button secondary" href={`/challenges/${game.slug}`}>Daily challenge</a></div>}</section>}
 {(path.startsWith('/play/')||path.startsWith('/challenges/'))&&game&&<GamePlayer game={game.slug} ranked={path.startsWith('/challenges/')} instructions={path.startsWith('/challenges/')?challenges.find(c=>c.slug===game.slug)?.instructions:game.instructions} configuration={challenges.find(c=>c.slug===game.slug)?.configuration} canStart={game.available!==false&&(!path.startsWith('/challenges/')||challenges.find(c=>c.slug===game.slug)?.status==='published')}/>}
 {path==='/challenges'&&<section><div className="eyebrow">TODAY'S LINEUP · UTC</div><h1>Rise to the challenge.</h1><p>Three ranked attempts per game each day. Started and interrupted sessions count toward the limit.</p><div className="challenge-list">{games.map(g=><div className="panel" key={g.slug}><span className="tag">{g.category}</span><h2>{g.name}</h2><p>{challenges.find(c=>c.slug===g.slug)?.configuration?.durationSeconds||'…'} seconds · {challenges.find(c=>c.slug===g.slug)?.configuration?.rounds||'8 pairs'}</p><p>{challenges.find(c=>c.slug===g.slug)?.attemptsRemaining==null?'Sign in to see remaining attempts':`${challenges.find(c=>c.slug===g.slug)?.attemptsRemaining} of 3 attempts remaining`} · Rules v2</p>{g.available!==false&&challenges.find(c=>c.slug===g.slug)?.status==='published'?<a className="button" href={`/challenges/${g.slug}`}>Enter challenge ↗</a>:<p>{g.available===false?'Game unavailable':challenges.find(c=>c.slug===g.slug)?.status||'Loading challenge…'}</p>}</div>)}</div></section>}
 {['/login','/signup'].includes(path)&&<section className="panel auth"><div className="eyebrow">YOUR NEXT CHAPTER</div><h1>{path==='/signup'?'Join the game.':'Welcome back.'}</h1><form onSubmit={auth}><label>Username<input name="username" pattern="[a-zA-Z0-9_]+" minLength={3} maxLength={24} required autoComplete="username"/></label><label>Password<input name="password" type="password" minLength={8} maxLength={128} required autoComplete={path==='/signup'?'new-password':'current-password'}/></label><button>{path==='/signup'?'Create account':'Log in'}</button></form><p><a href={path==='/signup'?'/login':'/signup'}>{path==='/signup'?'Already a member? Log in':'New here? Join free'}</a></p></section>}
 {['/dashboard','/progress'].includes(path)&&<Progress/>}
 {path==='/settings'&&<AccountSettings/>}
 {path==='/leaderboards'&&<section><div className="eyebrow">THE DAILY STANDINGS · UTC</div><h1>A little friendly competition.</h1><select aria-label="Select game" value={selected} onChange={e=>setSelected(e.target.value)}>{games.map(g=><option key={g.slug} value={g.slug}>{g.name}</option>)}</select><p>Best validated attempt per player. <a href="/competition-rules">See ranking rules →</a></p>{rows.length?<div className="table-wrap"><table><thead><tr><th>Rank</th><th>Player</th><th>Score</th><th>Accuracy</th><th>Time</th></tr></thead><tbody>{rows.map(r=><tr key={r.username} className={r.username===user?.username?'you':''}><td>#{r.rank}</td><td>{r.username}{r.username===user?.username?' · you':''}</td><td>{r.score}</td><td>{r.accuracy}%</td><td>{(r.duration/1000).toFixed(1)}s</td></tr>)}</tbody></table></div>:<div className="panel"><h2>The board is open.</h2><p>No validated scores for today's challenge yet. Yours could be the first.</p><a href={`/challenges/${selected}`} className="button">Play challenge</a></div>}</section>}
 {path==='/admin'&&<AdminPanel/>}
 {['/how-it-works','/competition-rules','/privacy','/terms','/contact','/forgot-password'].includes(path)&&<section className="panel prose"><h1>{path.slice(1).replaceAll('-',' ')}</h1>{path==='/competition-rules'?<><p>Daily challenges reset at midnight UTC. Starting a session consumes one of three attempts. Game-specific server time limits; no pause. Published challenge cards and instructions show the fixed timing and round configuration. Admin defaults apply only when a new challenge is generated. Your best validated result counts.</p><p>Speed, Attention and Math: score descending, accuracy descending, submission time ascending. Memory: complete correct patterns descending, incorrect cells ascending, answer response time ascending. Required two-second pattern displays are excluded from response time. Pairs: completed first, duration ascending, moves ascending; unfinished games compare pairs found.</p><p>Rules v2. Suspended players and invalidated attempts are excluded from rankings. Everyone receives the same daily challenge content; repeated attempts can become familiar. Your best valid attempt counts. Older versions have separate rankings. All time and weekly aggregation are deferred. Resume a ranked session on the same browser after refresh; its timer keeps running. At timeout, answered rounds or found pairs count. Rankings can be affected by network latency. No prizes.</p></>:path==='/how-it-works'?<p>Choose a game, read the instructions, and practice for free. Sign in to play daily challenges. The server evaluates your answers before adding your result to the leaderboard.</p>:path==='/privacy'?<p>Demo notice: the service stores usernames, password hashes, login sessions, challenge attempts and results. Daily leaderboards display usernames. Do not use sensitive personal information. Production requires a published retention and deletion policy.</p>:path==='/terms'?<p>This is a demonstration platform. Game scores describe performance, not health or intelligence. Play fairly. Production terms must be reviewed before public release.</p>:path==='/settings'?<p>Keyboard and touch controls are supported. The demo has no audio. Language and account editing are planned.</p>:path==='/forgot-password'?<p>Password recovery is not configured in this demo. Contact the operator of your deployment for account assistance.</p>:<p>{content.contact}</p>}</section>}
 {!['/','/games','/challenges','/signup','/login','/dashboard','/progress','/leaderboards','/admin','/how-it-works','/competition-rules','/privacy','/terms','/contact','/settings','/forgot-password'].includes(path)&&!game&&!path.startsWith('/games/category/')&&<section><h1>Page not found.</h1><a href="/games">Explore games →</a></section>}
 </main><footer><a className="brand" href="/">belancer game</a><p>A little time for your mind.</p><div><a href="/competition-rules">Competition rules</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a></div><small>© {new Date().getFullYear()} Belancer Game · Demo release</small></footer></>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
